plugins {
    id 'com.android.application'
}

android {
    namespace 'ru.farrukh.ai.witch'
    compileSdk 35

    defaultConfig {
        applicationId 'ru.farrukh.ai.witch'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '2.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'net.java.dev.jna:jna:5.18.1@aar'
    implementation 'com.alphacephei:vosk-android:0.3.75@aar'
}
